const STATUS_CODE_OK = 200;
const STATUS_CODE_CREATED = 201;
const BAD_REQUEST_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const INTERNAL_SERVER_ERROR_CODE = 500;

module.exports = {
  STATUS_CODE_OK,
  STATUS_CODE_CREATED,
  BAD_REQUEST_CODE,
  NOT_FOUND_ERROR_CODE,
  INTERNAL_SERVER_ERROR_CODE,
};
